apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../jbosseap-base/resources

commonLabels:
  application: sample-c

images:
- name: application-image
  newName: abkura/jboss-profiler
  newTag: latest